#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterShop20.DbDataTool
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MasterShopDb")]
	public partial class ShopDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertArtikel(Artikel instance);
    partial void UpdateArtikel(Artikel instance);
    partial void DeleteArtikel(Artikel instance);
    partial void InsertUntergruppe(Untergruppe instance);
    partial void UpdateUntergruppe(Untergruppe instance);
    partial void DeleteUntergruppe(Untergruppe instance);
    partial void InsertHauptgruppe(Hauptgruppe instance);
    partial void UpdateHauptgruppe(Hauptgruppe instance);
    partial void DeleteHauptgruppe(Hauptgruppe instance);
    partial void InsertNutzer(Nutzer instance);
    partial void UpdateNutzer(Nutzer instance);
    partial void DeleteNutzer(Nutzer instance);
    partial void InsertSteuersatz(Steuersatz instance);
    partial void UpdateSteuersatz(Steuersatz instance);
    partial void DeleteSteuersatz(Steuersatz instance);
    partial void InsertBestellung(Bestellung instance);
    partial void UpdateBestellung(Bestellung instance);
    partial void DeleteBestellung(Bestellung instance);
    partial void InsertBestellungsDetail(BestellungsDetail instance);
    partial void UpdateBestellungsDetail(BestellungsDetail instance);
    partial void DeleteBestellungsDetail(BestellungsDetail instance);
    #endregion
		
		public ShopDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShopDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShopDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShopDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Artikel> Artikels
		{
			get
			{
				return this.GetTable<Artikel>();
			}
		}
		
		public System.Data.Linq.Table<Untergruppe> Untergruppes
		{
			get
			{
				return this.GetTable<Untergruppe>();
			}
		}
		
		public System.Data.Linq.Table<Hauptgruppe> Hauptgruppes
		{
			get
			{
				return this.GetTable<Hauptgruppe>();
			}
		}
		
		public System.Data.Linq.Table<Nutzer> Nutzers
		{
			get
			{
				return this.GetTable<Nutzer>();
			}
		}
		
		public System.Data.Linq.Table<Steuersatz> Steuersatzs
		{
			get
			{
				return this.GetTable<Steuersatz>();
			}
		}
		
		public System.Data.Linq.Table<Bestellung> Bestellungs
		{
			get
			{
				return this.GetTable<Bestellung>();
			}
		}
		
		public System.Data.Linq.Table<BestellungsDetail> BestellungsDetails
		{
			get
			{
				return this.GetTable<BestellungsDetail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Artikel")]
	public partial class Artikel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdArtikel;
		
		private string _Titel;
		
		private int _IdUntergruppe;
		
		private decimal _NettoPreis;
		
		private int _IdSteuersatz;
		
		private string _Beschreibung;
		
		private string _Datenblatt;
		
		private System.Nullable<int> _IdOriginal;
		
		private string _BildLink;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdArtikelChanging(int value);
    partial void OnIdArtikelChanged();
    partial void OnTitelChanging(string value);
    partial void OnTitelChanged();
    partial void OnIdUntergruppeChanging(int value);
    partial void OnIdUntergruppeChanged();
    partial void OnNettoPreisChanging(decimal value);
    partial void OnNettoPreisChanged();
    partial void OnIdSteuersatzChanging(int value);
    partial void OnIdSteuersatzChanged();
    partial void OnBeschreibungChanging(string value);
    partial void OnBeschreibungChanged();
    partial void OnDatenblattChanging(string value);
    partial void OnDatenblattChanged();
    partial void OnIdOriginalChanging(System.Nullable<int> value);
    partial void OnIdOriginalChanged();
    partial void OnBildLinkChanging(string value);
    partial void OnBildLinkChanged();
    #endregion
		
		public Artikel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArtikel", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdArtikel
		{
			get
			{
				return this._IdArtikel;
			}
			set
			{
				if ((this._IdArtikel != value))
				{
					this.OnIdArtikelChanging(value);
					this.SendPropertyChanging();
					this._IdArtikel = value;
					this.SendPropertyChanged("IdArtikel");
					this.OnIdArtikelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titel", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Titel
		{
			get
			{
				return this._Titel;
			}
			set
			{
				if ((this._Titel != value))
				{
					this.OnTitelChanging(value);
					this.SendPropertyChanging();
					this._Titel = value;
					this.SendPropertyChanged("Titel");
					this.OnTitelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUntergruppe", DbType="Int NOT NULL")]
		public int IdUntergruppe
		{
			get
			{
				return this._IdUntergruppe;
			}
			set
			{
				if ((this._IdUntergruppe != value))
				{
					this.OnIdUntergruppeChanging(value);
					this.SendPropertyChanging();
					this._IdUntergruppe = value;
					this.SendPropertyChanged("IdUntergruppe");
					this.OnIdUntergruppeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NettoPreis", DbType="Decimal(18,2) NOT NULL")]
		public decimal NettoPreis
		{
			get
			{
				return this._NettoPreis;
			}
			set
			{
				if ((this._NettoPreis != value))
				{
					this.OnNettoPreisChanging(value);
					this.SendPropertyChanging();
					this._NettoPreis = value;
					this.SendPropertyChanged("NettoPreis");
					this.OnNettoPreisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSteuersatz", DbType="Int NOT NULL")]
		public int IdSteuersatz
		{
			get
			{
				return this._IdSteuersatz;
			}
			set
			{
				if ((this._IdSteuersatz != value))
				{
					this.OnIdSteuersatzChanging(value);
					this.SendPropertyChanging();
					this._IdSteuersatz = value;
					this.SendPropertyChanged("IdSteuersatz");
					this.OnIdSteuersatzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Beschreibung", DbType="VarChar(MAX)")]
		public string Beschreibung
		{
			get
			{
				return this._Beschreibung;
			}
			set
			{
				if ((this._Beschreibung != value))
				{
					this.OnBeschreibungChanging(value);
					this.SendPropertyChanging();
					this._Beschreibung = value;
					this.SendPropertyChanged("Beschreibung");
					this.OnBeschreibungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datenblatt", DbType="VarChar(MAX)")]
		public string Datenblatt
		{
			get
			{
				return this._Datenblatt;
			}
			set
			{
				if ((this._Datenblatt != value))
				{
					this.OnDatenblattChanging(value);
					this.SendPropertyChanging();
					this._Datenblatt = value;
					this.SendPropertyChanged("Datenblatt");
					this.OnDatenblattChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdOriginal", DbType="Int")]
		public System.Nullable<int> IdOriginal
		{
			get
			{
				return this._IdOriginal;
			}
			set
			{
				if ((this._IdOriginal != value))
				{
					this.OnIdOriginalChanging(value);
					this.SendPropertyChanging();
					this._IdOriginal = value;
					this.SendPropertyChanged("IdOriginal");
					this.OnIdOriginalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BildLink", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string BildLink
		{
			get
			{
				return this._BildLink;
			}
			set
			{
				if ((this._BildLink != value))
				{
					this.OnBildLinkChanging(value);
					this.SendPropertyChanging();
					this._BildLink = value;
					this.SendPropertyChanged("BildLink");
					this.OnBildLinkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Untergruppe")]
	public partial class Untergruppe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdUntergruppe;
		
		private string _Titel;
		
		private int _IdHauptgruppe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUntergruppeChanging(int value);
    partial void OnIdUntergruppeChanged();
    partial void OnTitelChanging(string value);
    partial void OnTitelChanged();
    partial void OnIdHauptgruppeChanging(int value);
    partial void OnIdHauptgruppeChanged();
    #endregion
		
		public Untergruppe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUntergruppe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUntergruppe
		{
			get
			{
				return this._IdUntergruppe;
			}
			set
			{
				if ((this._IdUntergruppe != value))
				{
					this.OnIdUntergruppeChanging(value);
					this.SendPropertyChanging();
					this._IdUntergruppe = value;
					this.SendPropertyChanged("IdUntergruppe");
					this.OnIdUntergruppeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titel", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Titel
		{
			get
			{
				return this._Titel;
			}
			set
			{
				if ((this._Titel != value))
				{
					this.OnTitelChanging(value);
					this.SendPropertyChanging();
					this._Titel = value;
					this.SendPropertyChanged("Titel");
					this.OnTitelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHauptgruppe", DbType="Int NOT NULL")]
		public int IdHauptgruppe
		{
			get
			{
				return this._IdHauptgruppe;
			}
			set
			{
				if ((this._IdHauptgruppe != value))
				{
					this.OnIdHauptgruppeChanging(value);
					this.SendPropertyChanging();
					this._IdHauptgruppe = value;
					this.SendPropertyChanged("IdHauptgruppe");
					this.OnIdHauptgruppeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hauptgruppe")]
	public partial class Hauptgruppe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdHauptgruppe;
		
		private string _Titel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdHauptgruppeChanging(int value);
    partial void OnIdHauptgruppeChanged();
    partial void OnTitelChanging(string value);
    partial void OnTitelChanged();
    #endregion
		
		public Hauptgruppe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdHauptgruppe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdHauptgruppe
		{
			get
			{
				return this._IdHauptgruppe;
			}
			set
			{
				if ((this._IdHauptgruppe != value))
				{
					this.OnIdHauptgruppeChanging(value);
					this.SendPropertyChanging();
					this._IdHauptgruppe = value;
					this.SendPropertyChanged("IdHauptgruppe");
					this.OnIdHauptgruppeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titel", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Titel
		{
			get
			{
				return this._Titel;
			}
			set
			{
				if ((this._Titel != value))
				{
					this.OnTitelChanging(value);
					this.SendPropertyChanging();
					this._Titel = value;
					this.SendPropertyChanged("Titel");
					this.OnTitelChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nutzer")]
	public partial class Nutzer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdNutzer;
		
		private string _Name;
		
		private string _Vorname;
		
		private string _Strasse;
		
		private string _HausNr;
		
		private int _PLZ;
		
		private string _Ort;
		
		private string _EMail;
		
		private string _Passwort;
		
		private bool _IsAdmin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNutzerChanging(int value);
    partial void OnIdNutzerChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnVornameChanging(string value);
    partial void OnVornameChanged();
    partial void OnStrasseChanging(string value);
    partial void OnStrasseChanged();
    partial void OnHausNrChanging(string value);
    partial void OnHausNrChanged();
    partial void OnPLZChanging(int value);
    partial void OnPLZChanged();
    partial void OnOrtChanging(string value);
    partial void OnOrtChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    partial void OnPasswortChanging(string value);
    partial void OnPasswortChanged();
    partial void OnIsAdminChanging(bool value);
    partial void OnIsAdminChanged();
    #endregion
		
		public Nutzer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNutzer", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdNutzer
		{
			get
			{
				return this._IdNutzer;
			}
			set
			{
				if ((this._IdNutzer != value))
				{
					this.OnIdNutzerChanging(value);
					this.SendPropertyChanging();
					this._IdNutzer = value;
					this.SendPropertyChanged("IdNutzer");
					this.OnIdNutzerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vorname", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Vorname
		{
			get
			{
				return this._Vorname;
			}
			set
			{
				if ((this._Vorname != value))
				{
					this.OnVornameChanging(value);
					this.SendPropertyChanging();
					this._Vorname = value;
					this.SendPropertyChanged("Vorname");
					this.OnVornameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Strasse", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Strasse
		{
			get
			{
				return this._Strasse;
			}
			set
			{
				if ((this._Strasse != value))
				{
					this.OnStrasseChanging(value);
					this.SendPropertyChanging();
					this._Strasse = value;
					this.SendPropertyChanged("Strasse");
					this.OnStrasseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HausNr", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string HausNr
		{
			get
			{
				return this._HausNr;
			}
			set
			{
				if ((this._HausNr != value))
				{
					this.OnHausNrChanging(value);
					this.SendPropertyChanging();
					this._HausNr = value;
					this.SendPropertyChanged("HausNr");
					this.OnHausNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLZ", DbType="Int NOT NULL")]
		public int PLZ
		{
			get
			{
				return this._PLZ;
			}
			set
			{
				if ((this._PLZ != value))
				{
					this.OnPLZChanging(value);
					this.SendPropertyChanging();
					this._PLZ = value;
					this.SendPropertyChanged("PLZ");
					this.OnPLZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ort", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Ort
		{
			get
			{
				return this._Ort;
			}
			set
			{
				if ((this._Ort != value))
				{
					this.OnOrtChanging(value);
					this.SendPropertyChanging();
					this._Ort = value;
					this.SendPropertyChanged("Ort");
					this.OnOrtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this.OnEMailChanging(value);
					this.SendPropertyChanging();
					this._EMail = value;
					this.SendPropertyChanged("EMail");
					this.OnEMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passwort", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Passwort
		{
			get
			{
				return this._Passwort;
			}
			set
			{
				if ((this._Passwort != value))
				{
					this.OnPasswortChanging(value);
					this.SendPropertyChanging();
					this._Passwort = value;
					this.SendPropertyChanged("Passwort");
					this.OnPasswortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdmin", DbType="Bit NOT NULL")]
		public bool IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this.OnIsAdminChanging(value);
					this.SendPropertyChanging();
					this._IsAdmin = value;
					this.SendPropertyChanged("IsAdmin");
					this.OnIsAdminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Steuersatz")]
	public partial class Steuersatz : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdSteuersatz;
		
		private string _Titel;
		
		private decimal _Steuersatz1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdSteuersatzChanging(int value);
    partial void OnIdSteuersatzChanged();
    partial void OnTitelChanging(string value);
    partial void OnTitelChanged();
    partial void OnSteuersatz1Changing(decimal value);
    partial void OnSteuersatz1Changed();
    #endregion
		
		public Steuersatz()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSteuersatz", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdSteuersatz
		{
			get
			{
				return this._IdSteuersatz;
			}
			set
			{
				if ((this._IdSteuersatz != value))
				{
					this.OnIdSteuersatzChanging(value);
					this.SendPropertyChanging();
					this._IdSteuersatz = value;
					this.SendPropertyChanged("IdSteuersatz");
					this.OnIdSteuersatzChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titel", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string Titel
		{
			get
			{
				return this._Titel;
			}
			set
			{
				if ((this._Titel != value))
				{
					this.OnTitelChanging(value);
					this.SendPropertyChanging();
					this._Titel = value;
					this.SendPropertyChanged("Titel");
					this.OnTitelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Steuersatz", Storage="_Steuersatz1", DbType="Decimal(18,2) NOT NULL")]
		public decimal Steuersatz1
		{
			get
			{
				return this._Steuersatz1;
			}
			set
			{
				if ((this._Steuersatz1 != value))
				{
					this.OnSteuersatz1Changing(value);
					this.SendPropertyChanging();
					this._Steuersatz1 = value;
					this.SendPropertyChanged("Steuersatz1");
					this.OnSteuersatz1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bestellung")]
	public partial class Bestellung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdBestellung;
		
		private int _IdNutzer;
		
		private System.DateTime _Datum;
		
		private string _ZahlArt;
		
		private string _ReName;
		
		private string _ReVorname;
		
		private string _ReStrasseNr;
		
		private string _RePlzOrt;
		
		private bool _Bezahlt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdBestellungChanging(int value);
    partial void OnIdBestellungChanged();
    partial void OnIdNutzerChanging(int value);
    partial void OnIdNutzerChanged();
    partial void OnDatumChanging(System.DateTime value);
    partial void OnDatumChanged();
    partial void OnZahlArtChanging(string value);
    partial void OnZahlArtChanged();
    partial void OnReNameChanging(string value);
    partial void OnReNameChanged();
    partial void OnReVornameChanging(string value);
    partial void OnReVornameChanged();
    partial void OnReStrasseNrChanging(string value);
    partial void OnReStrasseNrChanged();
    partial void OnRePlzOrtChanging(string value);
    partial void OnRePlzOrtChanged();
    partial void OnBezahltChanging(bool value);
    partial void OnBezahltChanged();
    #endregion
		
		public Bestellung()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBestellung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdBestellung
		{
			get
			{
				return this._IdBestellung;
			}
			set
			{
				if ((this._IdBestellung != value))
				{
					this.OnIdBestellungChanging(value);
					this.SendPropertyChanging();
					this._IdBestellung = value;
					this.SendPropertyChanged("IdBestellung");
					this.OnIdBestellungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNutzer", DbType="Int NOT NULL")]
		public int IdNutzer
		{
			get
			{
				return this._IdNutzer;
			}
			set
			{
				if ((this._IdNutzer != value))
				{
					this.OnIdNutzerChanging(value);
					this.SendPropertyChanging();
					this._IdNutzer = value;
					this.SendPropertyChanged("IdNutzer");
					this.OnIdNutzerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datum", DbType="Date NOT NULL")]
		public System.DateTime Datum
		{
			get
			{
				return this._Datum;
			}
			set
			{
				if ((this._Datum != value))
				{
					this.OnDatumChanging(value);
					this.SendPropertyChanging();
					this._Datum = value;
					this.SendPropertyChanged("Datum");
					this.OnDatumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZahlArt", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string ZahlArt
		{
			get
			{
				return this._ZahlArt;
			}
			set
			{
				if ((this._ZahlArt != value))
				{
					this.OnZahlArtChanging(value);
					this.SendPropertyChanging();
					this._ZahlArt = value;
					this.SendPropertyChanged("ZahlArt");
					this.OnZahlArtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReName", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string ReName
		{
			get
			{
				return this._ReName;
			}
			set
			{
				if ((this._ReName != value))
				{
					this.OnReNameChanging(value);
					this.SendPropertyChanging();
					this._ReName = value;
					this.SendPropertyChanged("ReName");
					this.OnReNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReVorname", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string ReVorname
		{
			get
			{
				return this._ReVorname;
			}
			set
			{
				if ((this._ReVorname != value))
				{
					this.OnReVornameChanging(value);
					this.SendPropertyChanging();
					this._ReVorname = value;
					this.SendPropertyChanged("ReVorname");
					this.OnReVornameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReStrasseNr", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string ReStrasseNr
		{
			get
			{
				return this._ReStrasseNr;
			}
			set
			{
				if ((this._ReStrasseNr != value))
				{
					this.OnReStrasseNrChanging(value);
					this.SendPropertyChanging();
					this._ReStrasseNr = value;
					this.SendPropertyChanged("ReStrasseNr");
					this.OnReStrasseNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RePlzOrt", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string RePlzOrt
		{
			get
			{
				return this._RePlzOrt;
			}
			set
			{
				if ((this._RePlzOrt != value))
				{
					this.OnRePlzOrtChanging(value);
					this.SendPropertyChanging();
					this._RePlzOrt = value;
					this.SendPropertyChanged("RePlzOrt");
					this.OnRePlzOrtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bezahlt", DbType="Bit NOT NULL")]
		public bool Bezahlt
		{
			get
			{
				return this._Bezahlt;
			}
			set
			{
				if ((this._Bezahlt != value))
				{
					this.OnBezahltChanging(value);
					this.SendPropertyChanging();
					this._Bezahlt = value;
					this.SendPropertyChanged("Bezahlt");
					this.OnBezahltChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BestellungsDetail")]
	public partial class BestellungsDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdDetails;
		
		private int _IdBestellung;
		
		private string _ArtikelName;
		
		private decimal _NettoPreis;
		
		private decimal _MwSt;
		
		private int _Anzahl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDetailsChanging(int value);
    partial void OnIdDetailsChanged();
    partial void OnIdBestellungChanging(int value);
    partial void OnIdBestellungChanged();
    partial void OnArtikelNameChanging(string value);
    partial void OnArtikelNameChanged();
    partial void OnNettoPreisChanging(decimal value);
    partial void OnNettoPreisChanged();
    partial void OnMwStChanging(decimal value);
    partial void OnMwStChanged();
    partial void OnAnzahlChanging(int value);
    partial void OnAnzahlChanged();
    #endregion
		
		public BestellungsDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDetails", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdDetails
		{
			get
			{
				return this._IdDetails;
			}
			set
			{
				if ((this._IdDetails != value))
				{
					this.OnIdDetailsChanging(value);
					this.SendPropertyChanging();
					this._IdDetails = value;
					this.SendPropertyChanged("IdDetails");
					this.OnIdDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBestellung", DbType="Int NOT NULL")]
		public int IdBestellung
		{
			get
			{
				return this._IdBestellung;
			}
			set
			{
				if ((this._IdBestellung != value))
				{
					this.OnIdBestellungChanging(value);
					this.SendPropertyChanging();
					this._IdBestellung = value;
					this.SendPropertyChanged("IdBestellung");
					this.OnIdBestellungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArtikelName", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string ArtikelName
		{
			get
			{
				return this._ArtikelName;
			}
			set
			{
				if ((this._ArtikelName != value))
				{
					this.OnArtikelNameChanging(value);
					this.SendPropertyChanging();
					this._ArtikelName = value;
					this.SendPropertyChanged("ArtikelName");
					this.OnArtikelNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NettoPreis", DbType="Decimal(18,2) NOT NULL")]
		public decimal NettoPreis
		{
			get
			{
				return this._NettoPreis;
			}
			set
			{
				if ((this._NettoPreis != value))
				{
					this.OnNettoPreisChanging(value);
					this.SendPropertyChanging();
					this._NettoPreis = value;
					this.SendPropertyChanged("NettoPreis");
					this.OnNettoPreisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MwSt", DbType="Decimal(18,2) NOT NULL")]
		public decimal MwSt
		{
			get
			{
				return this._MwSt;
			}
			set
			{
				if ((this._MwSt != value))
				{
					this.OnMwStChanging(value);
					this.SendPropertyChanging();
					this._MwSt = value;
					this.SendPropertyChanged("MwSt");
					this.OnMwStChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anzahl", DbType="Int NOT NULL")]
		public int Anzahl
		{
			get
			{
				return this._Anzahl;
			}
			set
			{
				if ((this._Anzahl != value))
				{
					this.OnAnzahlChanging(value);
					this.SendPropertyChanging();
					this._Anzahl = value;
					this.SendPropertyChanged("Anzahl");
					this.OnAnzahlChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
